version: '3'

services:
  app:
    image: embraslabs/ruby:3.2.2
    container_name: ruby3.2.2-srv
    stdin_open: true
    depends_on:
      - db
    volumes:
      - .:/app
      - gems:/.gems

  db:
    image: jacobalberty/firebird:v3.0.10
    container_name: firebrd3.0-srv
    environment:
      - ISC_PASSWORD=masterkey
      - TZ=America/Sao_Paulo
    volumes:
      - firebird:/firebird
      - ./spec/db/example.fdb:/firebird/data/test.fdb
      - ./db/example.fdb:/firebird/data/example.fdb
    ports:
      - "5050:3050"

volumes:
  gems:
  firebird:
